### ISSUE TITLE
Does mo-git-blame-mode have a mode hook?

### ISSUE THREAD

**Issue by zhaojiangbin** [mbunkus/mo-git-blame#14]
I want to enable `hl-line-mode` in the `mo-git-blame-mode` buffer. Not able to find the mode hook of it, I have to add a key binding in `mo-git-blame-mode-map` to call `hl-line-mode`. It feels clunky.

**Comment by mbunkus** [comment]
At the moment: no. I'd welcome a pull request for such functionality as I'm rather busy with other projects these days.
