### ISSUE TITLE
Conflict with neotree.

### ISSUE THREAD

**Issue by zw963** [mbunkus/mo-git-blame#19]
https://github.com/jaypei/emacs-neotree

Follow is a screenshots

![NeoTree-1] (https://raw.githubusercontent.com/wiki/jaypei/emacs-neotree/imgs/neotree-1.png)

**Comment by mbunkus** [comment]
Yeah well… This is nothing I'm going to fix. Sorry. This is mostly a project to scratch my own itch, and it does that well enough. I don't have the time or motivation to properly maintain it beyond that.

**Comment by zw963** [comment]
@mbunkus , after settings `mo-git-blame-delete-other-windows` to `t`, it worked.
Thanks.
